# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "bundler-audit", "~> 0.9"
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.13"
  gem "rubocop", "~> 1.60"
  gem "rubocop-rspec", "~> 3.0"
  gem "simplecov", "~> 1.0"
  gem "simplecov_json_formatter", "~> 0.1"
  gem "webmock", "~> 3.23"
end
